name: Deploy to hiverift.com
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /home/hiverift0805/nextjs_app
          git pull origin main
          npm install
          rm -rf .next
          npm run build
          cp /home/hiverift0805/nextjs_app/.htaccess /home/hiverift0805/public_html/.htaccess
          sudo /bin/pm2 restart hiverift
          sudo /bin/pm2 save